### ISSUE TITLE
Is linux supported?

### ISSUE THREAD

**Issue by dmikov** [Microsoft/generator-docker#108]
I am trying to use generator in linux environment, but it fails F5 with an error - Could not find the preLaunchTask 'composeForDebug'.
In tasks.json I see it defined but only for windows and osx. Is there any steps I need to do to run it on linux? (Ubuntu)

**Comment by dbreshears** [comment]
We haven't currently attempted on linux but would be curious to see what occurs when updating tasks.json with an entry similar to osx.       It is something we  would like to enable but just haven't yet had the opportunity to look into.

**Comment by divinebovine** [comment]
@dbreshears I think this issue can closed now.

**Comment by dbreshears** [comment]
Great.  Thank you!
