### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by matthewjcooper** [Microsoft/generator-docker#127]

**Comment by SteveLasker** [comment]
Hi Matthew,
The project isn't dead, per se. We had been merging the content into the Docker Tools for VS Code extension. https://github.com/microsoft/vscode-docker. 
Were you looking to contribute? Or, are you looking for the PRs queued?
Steve

**Comment by matthewjcooper** [comment]
Ah, no not wanting to contribute, I've been using this and had some issues with performance while debugging .net core in docker with it, and had kept checking back for updates and wasn't seeing any traffic. Thanks for the link to the extension!
