### ISSUE TITLE
Wrong docker run path generated for node on windows

### ISSUE THREAD

**Issue by Lajt** [Microsoft/generator-docker#38]
Problem is wrong generated path for volume flag in docker run command.
Issue in windows 7 within cmd.

This is generated command in dockerTask.cmd:
`docker run -di -p %publicPort%:%containerPort% -v /C:/Users\Lajt\Code\playground\testdoc:/src %imageName%`
error after run command:
`invalid value "/C:/Users\\Lajt\\Code\\playground\\testdoc:/src" for flag -v: bad mode specified: /src
See 'docker run --help'.`

Solution:
generated command should looks like:
`docker run -di -p %publicPort%:%containerPort% -v /c/Users/Lajt/Code/playground/testdoc:/src %imageName%`

**Comment by PeterJausovec** [comment]
Thanks for reporting this! I fixed it in the latest release (v0.0.26).
