### ISSUE TITLE
Update to use docker beta and Linux

### ISSUE THREAD

**Issue by giggio** [Microsoft/generator-docker#50]
Docker beta does not require `docker-machine`. The current script depends on `docker-machine`. Please add this as an option, or maybe fallback when docker-machine answers with `No active host found` to `docker-machine active`.
With docker beta, the host will be available as `docker`, for example `http://docker`.

Another important use case is for linux users, which also don't need `docker-machine`, and also will not use docker beta. In this case, we should detect the OS, and if it is a linux machine, and `docker-machine active` reports no host found, parse the $DOCKER_HOST variable, or, if it does not exist, assume localhost.

**Comment by saurabsa** [comment]
Updated URL for D4W to 'http://localhost'
