### ISSUE TITLE
How volumes are mounted?

### ISSUE THREAD

**Issue by jacace** [Microsoft/generator-docker#51]
I checked Dockerfile.debug and DockerTask.ps1 and can't find how volumes are mounted

I also can't find much information about Microsoft.Dnx.Watcher

Thanks,

**Comment by NCarlsonMSFT** [comment]
It is done in the compose file. See https://docs.docker.com/compose/compose-file/#volumes-volume-driver for more information.

As for dnx-watch whit the new RC2 that has been deprecated in favor of dotnet watch (see https://github.com/aspnet/dotnet-watch). Did you have a particular question about it?
