### ISSUE TITLE
VSCode Debug Error After Upgrading to RTM  (Unknown option 'client-ui'.)

### ISSUE THREAD

**Issue by matthewjcooper** [Microsoft/generator-docker#98]
OS: OSX El Capitan 10.11.5
Docker: Docker for mac 1.12.0-rc2-beta17
IDE: VSCode 1.2.1 
C# Omnisharp Extention 1.2.1
Dotnet --version output:  1.0.0-preview2-003121
generator-aspnet@0.2.0
generator-docker@0.0.33

Steps to reproduce:
1. yo aspnet
2. choose Web API Application
3. Name application dockertest
4. cd dockertest
5. rm Dockerfile
6. yo docker
```
? What language is your project using? .NET Core
? Which version of .NET Core is your project using? rtm
? Which port is your app listening to? 5000
? What do you want to name your image? dockertest
? What do you want to name your service? dockertest
? What do you want to name your compose project? dockertest
   create .dockerignore
   create .vscode/launch.json
   create Dockerfile.debug
   create Dockerfile
   create docker-compose.debug.yml
   create docker-compose.yml
   create dockerTask.ps1
   create dockerTask.sh
   create .vscode/tasks.json
We noticed your project.json file didn't use portable .pdb files. We've fixed that for you.
Your project is now ready to run in a Docker container!
Run dockerTask.sh to build a Docker image and run your app in a container.

```

7. Open project in vs code
8. Go to debug tab
9. Run debugger

Expected outcome: App begins debugging.

Actual outcome: VS Code shows the followoing Error:

> Unable to start debugging. Unexpected CLRDBG output from command "-gdb-set client-ui "VSCode"". Unknown option 'client-ui'.

**Comment by SteveLasker** [comment]
Hi Matthew,
Thanks for the detailed info. The only other question is how did you create the project you yo docerkized?  Was it created in Windows, with another scaffolder like aspnet?

**Comment by matthewjcooper** [comment]
I created the project using generator-aspnet 0.2.0 with the options I mentioned above in steps 1-3.  Thanks!

**Comment by SteveLasker** [comment]
Ahh, I see. We haven't yet tested yo aspnet yet. I'm on my phone, but will check when I get back in the office. Heres a repo that worked with rc2 that you might want to use for reference. https://github.com/SteveLasker/polyglot-api-dotnet

**Comment by matthewjcooper** [comment]
Thanks.  Is there a method of creating an rtm project on the Mac that should work with the rtm option in the docket generator?

**Comment by SteveLasker** [comment]
The reality is we just got the updates for yo docker in time for DockerCon, and had just synched with Sayed about yo aspnet. We had created a project on VS and then used it from VS Code for testing. 
The answer will be yo aspnet and dotnet new. But, were obviously not there yet.

**Comment by matthewjcooper** [comment]
OK sounds good. I can roll back to rc2 for now, it was working great. and i'll keep an eye out for an update. Want me to close this issue?

**Comment by nabels-coolblue** [comment]
I have run into the exact same issue with:
dotnet --version: 1.0.0-preview2-003121
Windows Version: 10.0.10586 Build 10586
Omnisharp version: 1.2.1 
generator-aspnet@0.2.1
yeoman-generator@0.19.2
generator-docker@0.0.33

`Unable to start debugging. Unexpected CLRDBG output from command "-gdb-set client-ui "VSCode"". Unknown option 'client-ui'.`

**Comment by dbreshears** [comment]
It appears we have a fix for this now.  There was a mismatch with VSCode and the debugger downloaded by the script.   Can you retry after removing any old images you have that might have the older clrdbg in them

**Comment by matthewjcooper** [comment]
Yup after removing the images and rebuilding the debugger is working again! Thank you!
